// Generated from a clean migration reset. Do not edit by hand.
//
// Run `npm run types:generate` to refresh it; `npm run verify:db` fails if it
// does not match the database. It exists so the TypeScript Operation manifest
// can be checked against what Postgres actually holds, in a unit test that
// needs no database.

export type GeneratedOperationContract = {
  riskClass: string;
  exposures: readonly string[];
  reversible: boolean;
  owningDomain: string;
};

export const databaseOperationContracts: Readonly<Record<string, GeneratedOperationContract>> = {
  'account.deletion.cancel.v1': {
    riskClass: 'low',
    exposures: ['ui'],
    reversible: false,
    owningDomain: 'account',
  },
  'account.deletion.schedule.v1': {
    riskClass: 'high',
    exposures: ['ui'],
    reversible: true,
    owningDomain: 'account',
  },
  'action-template.archive.v1': {
    riskClass: 'medium',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'action_template',
  },
  'action-template.create.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'action_template',
  },
  'action-template.materialize.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp', 'automation'],
    reversible: true,
    owningDomain: 'action_template',
  },
  'action-template.status.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'action_template',
  },
  'action-template.update.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'action_template',
  },
  'action.archive.v1': {
    riskClass: 'medium',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'planner',
  },
  'action.create.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'planner',
  },
  'action.move.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'plan_edit',
  },
  'action.status.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'daily_execution',
  },
  'action.update.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'daily_execution',
  },
  'capture-proposal.apply.v1': {
    riskClass: 'medium',
    exposures: ['ui', 'chat'],
    reversible: false,
    owningDomain: 'capture_proposal',
  },
  'capture-proposal.dismiss.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat'],
    reversible: true,
    owningDomain: 'capture_proposal',
  },
  'capture-proposal.item-update.v1': {
    riskClass: 'low',
    exposures: ['ui'],
    reversible: true,
    owningDomain: 'capture_proposal',
  },
  'capture.create.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'planner',
  },
  'capture.file-to-action.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'capture_action_filing',
  },
  'capture.file-to-note.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'knowledge',
  },
  'conversation.delete.v1': {
    riskClass: 'high',
    exposures: ['ui', 'chat'],
    reversible: false,
    owningDomain: 'conversation',
  },
  'conversation.rename.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'conversation',
  },
  'conversation.status.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'conversation',
  },
  'daily-focus.set.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'daily_execution',
  },
  'goal.archive.v1': {
    riskClass: 'medium',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'planner',
  },
  'goal.create.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'planner',
  },
  'goal.status.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'planner',
  },
  'goal.update.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'plan_edit',
  },
  'memory.create.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'memory',
  },
  'memory.update.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'memory',
  },
  'note.action-link.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'note_relation',
  },
  'note.action-unlink.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'note_relation',
  },
  'note.ai-exclusion.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'note',
  },
  'note.appearance.v1': {
    riskClass: 'low',
    exposures: ['ui'],
    reversible: false,
    owningDomain: 'note_appearance',
  },
  'note.archive.v1': {
    riskClass: 'medium',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'note',
  },
  'note.create.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'note',
  },
  'note.favorite.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'note',
  },
  'note.goal-link.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'note_relation',
  },
  'note.goal-unlink.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'note_relation',
  },
  'note.import-cancel.v1': {
    riskClass: 'low',
    exposures: ['ui'],
    reversible: false,
    owningDomain: 'note_import',
  },
  'note.import-commit.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat'],
    reversible: true,
    owningDomain: 'note_import',
  },
  'note.import-preview.v1': {
    riskClass: 'low',
    exposures: ['ui'],
    reversible: true,
    owningDomain: 'note_import',
  },
  'note.link.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'knowledge',
  },
  'note.move.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'note',
  },
  'note.tags.set.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'knowledge',
  },
  'note.unlink.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'knowledge',
  },
  'note.update.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'note',
  },
  'notification.dismiss.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'notification',
  },
  'notification.preferences.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'notification',
  },
  'notification.read.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'notification',
  },
  'notification.refresh.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp', 'automation'],
    reversible: true,
    owningDomain: 'notification',
  },
  'operation.undo.v1': {
    riskClass: 'medium',
    exposures: ['ui'],
    reversible: false,
    owningDomain: 'operation_undo',
  },
  'review.complete-period.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat'],
    reversible: true,
    owningDomain: 'period_review',
  },
  'review.complete-weekly.v1': {
    riskClass: 'medium',
    exposures: ['ui', 'chat'],
    reversible: true,
    owningDomain: 'review',
  },
  'trash.empty.v1': {
    riskClass: 'high',
    exposures: ['ui', 'chat'],
    reversible: false,
    owningDomain: 'trash',
  },
  'trash.move.v1': {
    riskClass: 'medium',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'trash',
  },
  'trash.restore.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'trash',
  },
  'vision.upsert.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
    owningDomain: 'planner',
  },
  'workspace.ai-budget.v1': {
    riskClass: 'medium',
    exposures: ['ui', 'chat'],
    reversible: true,
    owningDomain: 'ai_budget',
  },
  'workspace.onboarding-complete.v1': {
    riskClass: 'medium',
    exposures: ['ui'],
    reversible: true,
    owningDomain: 'guided_onboarding',
  },
  'workspace.preferences.v1': {
    riskClass: 'medium',
    exposures: ['ui', 'chat'],
    reversible: true,
    owningDomain: 'workspace',
  },
  'workspace.snapshot.read.v1': {
    riskClass: 'read',
    exposures: ['mcp'],
    reversible: false,
    owningDomain: 'workspace',
  },
};

export const databaseUndoStrategies: Readonly<Record<string, string>> = {
  'account.deletion.schedule.v1': 'inverse-operation',
  'action-template.archive.v1': 'snapshot',
  'action-template.create.v1': 'trash-create',
  'action-template.materialize.v1': 'inverse-operation',
  'action-template.status.v1': 'snapshot',
  'action-template.update.v1': 'snapshot',
  'action.archive.v1': 'snapshot',
  'action.create.v1': 'trash-create',
  'action.move.v1': 'snapshot',
  'action.status.v1': 'snapshot',
  'action.update.v1': 'snapshot',
  'capture-proposal.dismiss.v1': 'snapshot',
  'capture-proposal.item-update.v1': 'snapshot',
  'capture.create.v1': 'trash-create',
  'capture.file-to-action.v1': 'snapshot',
  'capture.file-to-note.v1': 'snapshot',
  'conversation.rename.v1': 'snapshot',
  'conversation.status.v1': 'snapshot',
  'daily-focus.set.v1': 'snapshot',
  'goal.archive.v1': 'snapshot',
  'goal.create.v1': 'trash-create',
  'goal.status.v1': 'snapshot',
  'goal.update.v1': 'snapshot',
  'memory.create.v1': 'trash-create',
  'memory.update.v1': 'snapshot',
  'note.action-link.v1': 'inverse-operation',
  'note.action-unlink.v1': 'inverse-operation',
  'note.ai-exclusion.v1': 'snapshot',
  'note.archive.v1': 'snapshot',
  'note.create.v1': 'trash-create',
  'note.favorite.v1': 'snapshot',
  'note.goal-link.v1': 'inverse-operation',
  'note.goal-unlink.v1': 'inverse-operation',
  'note.import-commit.v1': 'snapshot',
  'note.import-preview.v1': 'trash-create',
  'note.link.v1': 'inverse-operation',
  'note.move.v1': 'snapshot',
  'note.tags.set.v1': 'inverse-operation',
  'note.unlink.v1': 'inverse-operation',
  'note.update.v1': 'snapshot',
  'notification.dismiss.v1': 'snapshot',
  'notification.preferences.v1': 'snapshot',
  'notification.read.v1': 'snapshot',
  'notification.refresh.v1': 'trash-create',
  'review.complete-period.v1': 'snapshot',
  'review.complete-weekly.v1': 'snapshot',
  'trash.move.v1': 'inverse-operation',
  'trash.restore.v1': 'snapshot',
  'vision.upsert.v1': 'snapshot',
  'workspace.ai-budget.v1': 'snapshot',
  'workspace.onboarding-complete.v1': 'snapshot',
  'workspace.preferences.v1': 'snapshot',
};
