// Generated from a clean migration reset. Do not edit by hand.
//
// Run `npm run types:generate` to refresh it; `npm run verify:db` fails if it
// does not match the database. It exists so the TypeScript Operation manifest
// can be checked against what Postgres actually holds, in a unit test that
// needs no database.

export type GeneratedOperationContract = {
  riskClass: string;
  exposures: readonly string[];
  reversible: boolean;
};

export const databaseOperationContracts: Readonly<Record<string, GeneratedOperationContract>> = {
  'account.deletion.cancel.v1': { riskClass: 'low', exposures: ['ui'], reversible: false },
  'account.deletion.schedule.v1': { riskClass: 'high', exposures: ['ui'], reversible: true },
  'action-template.archive.v1': {
    riskClass: 'medium',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
  },
  'action-template.create.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
  },
  'action-template.materialize.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp', 'automation'],
    reversible: true,
  },
  'action-template.status.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
  },
  'action-template.update.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
  },
  'action.archive.v1': { riskClass: 'medium', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'action.create.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'action.move.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'action.status.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'action.update.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'capture-proposal.apply.v1': {
    riskClass: 'medium',
    exposures: ['ui', 'chat'],
    reversible: false,
  },
  'capture-proposal.dismiss.v1': { riskClass: 'low', exposures: ['ui', 'chat'], reversible: true },
  'capture-proposal.item-update.v1': { riskClass: 'low', exposures: ['ui'], reversible: true },
  'capture.create.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'capture.file-to-action.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
  },
  'capture.file-to-note.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
  },
  'conversation.delete.v1': { riskClass: 'high', exposures: ['ui', 'chat'], reversible: false },
  'conversation.rename.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
  },
  'conversation.status.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
  },
  'daily-focus.set.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'goal.archive.v1': { riskClass: 'medium', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'goal.create.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'goal.status.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'goal.update.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'memory.create.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'memory.update.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'note.action-link.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'note.action-unlink.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'note.ai-exclusion.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'note.appearance.v1': { riskClass: 'low', exposures: ['ui'], reversible: false },
  'note.archive.v1': { riskClass: 'medium', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'note.create.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'note.favorite.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'note.goal-link.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'note.goal-unlink.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'note.import-cancel.v1': { riskClass: 'low', exposures: ['ui'], reversible: false },
  'note.import-commit.v1': { riskClass: 'low', exposures: ['ui', 'chat'], reversible: true },
  'note.import-preview.v1': { riskClass: 'low', exposures: ['ui'], reversible: true },
  'note.link.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'note.move.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'note.tags.set.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'note.unlink.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'note.update.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'notification.dismiss.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
  },
  'notification.preferences.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp'],
    reversible: true,
  },
  'notification.read.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'notification.refresh.v1': {
    riskClass: 'low',
    exposures: ['ui', 'chat', 'mcp', 'automation'],
    reversible: true,
  },
  'operation.undo.v1': { riskClass: 'medium', exposures: ['ui'], reversible: false },
  'review.complete-period.v1': { riskClass: 'low', exposures: ['ui', 'chat'], reversible: true },
  'review.complete-weekly.v1': { riskClass: 'medium', exposures: ['ui', 'chat'], reversible: true },
  'trash.empty.v1': { riskClass: 'high', exposures: ['ui', 'chat'], reversible: false },
  'trash.move.v1': { riskClass: 'medium', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'trash.restore.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'vision.upsert.v1': { riskClass: 'low', exposures: ['ui', 'chat', 'mcp'], reversible: true },
  'workspace.ai-budget.v1': { riskClass: 'medium', exposures: ['ui', 'chat'], reversible: true },
  'workspace.onboarding-complete.v1': { riskClass: 'medium', exposures: ['ui'], reversible: true },
  'workspace.preferences.v1': { riskClass: 'medium', exposures: ['ui', 'chat'], reversible: true },
  'workspace.snapshot.read.v1': { riskClass: 'read', exposures: ['mcp'], reversible: false },
};

export const databaseUndoStrategies: Readonly<Record<string, string>> = {
  'account.deletion.schedule.v1': 'inverse-operation',
  'action-template.archive.v1': 'snapshot',
  'action-template.create.v1': 'trash-create',
  'action-template.materialize.v1': 'inverse-operation',
  'action-template.status.v1': 'snapshot',
  'action-template.update.v1': 'snapshot',
  'action.archive.v1': 'snapshot',
  'action.create.v1': 'trash-create',
  'action.move.v1': 'snapshot',
  'action.status.v1': 'snapshot',
  'action.update.v1': 'snapshot',
  'capture-proposal.dismiss.v1': 'snapshot',
  'capture-proposal.item-update.v1': 'snapshot',
  'capture.create.v1': 'trash-create',
  'capture.file-to-action.v1': 'snapshot',
  'capture.file-to-note.v1': 'snapshot',
  'conversation.rename.v1': 'snapshot',
  'conversation.status.v1': 'snapshot',
  'daily-focus.set.v1': 'snapshot',
  'goal.archive.v1': 'snapshot',
  'goal.create.v1': 'trash-create',
  'goal.status.v1': 'snapshot',
  'goal.update.v1': 'snapshot',
  'memory.create.v1': 'trash-create',
  'memory.update.v1': 'snapshot',
  'note.action-link.v1': 'inverse-operation',
  'note.action-unlink.v1': 'inverse-operation',
  'note.ai-exclusion.v1': 'snapshot',
  'note.archive.v1': 'snapshot',
  'note.create.v1': 'trash-create',
  'note.favorite.v1': 'snapshot',
  'note.goal-link.v1': 'inverse-operation',
  'note.goal-unlink.v1': 'inverse-operation',
  'note.import-commit.v1': 'snapshot',
  'note.import-preview.v1': 'trash-create',
  'note.link.v1': 'inverse-operation',
  'note.move.v1': 'snapshot',
  'note.tags.set.v1': 'inverse-operation',
  'note.unlink.v1': 'inverse-operation',
  'note.update.v1': 'snapshot',
  'notification.dismiss.v1': 'snapshot',
  'notification.preferences.v1': 'snapshot',
  'notification.read.v1': 'snapshot',
  'notification.refresh.v1': 'trash-create',
  'review.complete-period.v1': 'snapshot',
  'review.complete-weekly.v1': 'snapshot',
  'trash.move.v1': 'inverse-operation',
  'trash.restore.v1': 'snapshot',
  'vision.upsert.v1': 'snapshot',
  'workspace.ai-budget.v1': 'snapshot',
  'workspace.onboarding-complete.v1': 'snapshot',
  'workspace.preferences.v1': 'snapshot',
};
